export const HELIOS_KNOWLEDGE_BASE = {
  introduction: {
    executiveSummary: `HELIOS represents a comprehensive asteroid-anchored space settlement designed for long-term human habitation. The settlement utilizes a captured near-Earth asteroid as both structural foundation and resource reservoir, featuring rotating habitats for artificial gravity, advanced life support systems, and the HELIOS AI management system for autonomous operations.`,
    scope: `The project encompasses complete settlement design including orbital mechanics, structural engineering, life support, radiation protection, population management, governance frameworks, and economic models. The scope includes initial deployment of 500-1000 settlers with expansion plans to support 10,000+ inhabitants.`
  },
  
  settlementOverview: {
    missionStatement: `To establish a sustainable, self-sufficient space settlement that serves as a model for future space colonization, advancing human presence beyond Earth while demonstrating viable long-term habitation in deep space environments.`,
    vision: `A thriving multi-generational space settlement that operates independently, conducts advanced research, facilitates commercial activities, and serves as a gateway for deeper space exploration. The settlement will eventually support 10,000+ residents with full economic and social infrastructure.`
  },
  
  orbitAndAsteroid: {
    orbitalCharacteristics: `Kepler Station operates in a heliocentric orbit closely matched to that of its anchor asteroid in order to minimize long-term propulsion requirements and simplify logistical operations. For the reference asteroid Bennu, this orbit has a semi-major axis of approximately 1.13 astronomical units, an eccentricity of 0.203, and an orbital period of approximately 1.20 Earth years. Matching the settlement orbit to the asteroid's heliocentric trajectory reduces relative velocity to near zero once rendezvous is achieved. During nominal operations, relative velocities between the station and the asteroid are maintained below 0.05 meters per second. This allows continuous proximity operations without high thrust maneuvers and significantly reduces station keeping requirements. Orbital perturbations are dominated by solar radiation pressure and gradual mass redistribution during mining. These perturbations are predictable and slow acting. Conservative estimates place annual station keeping requirements below 5 meters per second of delta-v per year. Assuming a total station mass of 5×10⁷ kilograms and the use of electric propulsion with an effective exhaust velocity of 30 kilometers per second, annual station keeping propellant consumption is approximately 8,300 kilograms of hydrogen. This requirement represents a negligible fraction of annual resource extraction capacity. Operating in heliocentric free space also provides stable thermal conditions and avoids repeated deep gravity well transitions, improving long-term operational stability and safety.`,
    asteroidSelection: `Bennu is selected as the reference anchor asteroid due to its extensive scientific characterization, accessible orbit, and confirmed volatile content. Bennu has a mean diameter of approximately 492 meters and an estimated total mass of 7.8×10¹⁰ kilograms. The asteroid has a bulk density of approximately 1.19 grams per cubic centimeter, indicating a rubble-pile structure with significant internal porosity. This structure enables relatively low energy excavation but also necessitates conservative extraction rates to preserve structural stability. Bennu's surface gravity is approximately 7×10⁻⁵ meters per second squared, and its escape velocity is approximately 0.2 meters per second. These values allow material extraction using low force mechanical systems while imposing strict limits on excavation velocities to prevent material loss.`,
    waterContent: `Data from NASA's OSIRIS-REx mission confirmed the presence of hydrated phyllosilicate minerals across Bennu's surface. These minerals form only in the presence of liquid water, confirming that Bennu contains chemically bound water. Laboratory analysis of returned samples indicates water contents of several percent by mass in certain regolith components. For conservative planning, an average water content of 3 percent by mass is assumed. Assuming an annual regolith processing rate of 1×10⁷ kilograms, annual water production is approximately 300,000 kilograms. This water supports life support systems, oxygen generation, hydrogen production, and energy storage. At a daily per capita water demand of 50 kilograms including drinking, hygiene, food production, and oxygen generation, this annual output can directly support 16 people without recycling. With closed-loop recycling efficiencies exceeding 90 percent, this same output supports a population of 1,000 people indefinitely by replacing only system losses.`,
    oxygenHydrogen: `Electrolysis of water yields approximately 0.89 kilograms of oxygen and 0.11 kilograms of hydrogen per kilogram of water processed. From 300,000 kilograms of water per year, approximately 267,000 kilograms of oxygen and 33,000 kilograms of hydrogen are produced annually. At a metabolic oxygen consumption rate of approximately 0.84 kilograms per person per day, annual oxygen demand for a population of 1,000 people is approximately 307,000 kilograms. Closed-loop atmospheric recycling reduces net oxygen replacement demand to less than 10 percent of this value, providing a substantial safety margin. Hydrogen produced during electrolysis exceeds propulsion and energy storage requirements, enabling reserve accumulation and long-term expansion capability.`,
    regolith: `In addition to volatiles, asteroid regolith provides large quantities of silicate and carbon-rich material. This material is processed into radiation shielding mass, structural fill, and construction feedstock. Radiation protection equivalent to near-Earth surface exposure requires shielding on the order of 2.5 meters of regolith. At an average regolith density of 1.5 grams per cubic centimeter, this corresponds to approximately 3,750 kilograms per square meter of shielding mass. For a habitat ring with an internal living area of 150,000 square meters, total shielding mass is approximately 5.6×10⁸ kilograms. This mass is readily available from the asteroid without Earth launch.`,
    advantages: `Anchoring Kepler Station to a near-Earth asteroid provides significant strategic and economic advantages compared to planetary or lunar surface settlements. From an energy perspective, delta-v requirements to reach and operate at a near-Earth asteroid are comparable to or lower than those required for sustained lunar surface operations. Once established, station keeping and logistics rely primarily on locally produced propellant, reducing recurring costs. From a resource perspective, asteroid-based water and regolith eliminate the need to launch large quantities of mass from Earth. Launching one kilogram of material to low Earth orbit currently requires on the order of tens of megajoules of energy and significant financial cost. Substituting locally sourced material dramatically improves scalability. From an operational perspective, free space habitation allows controlled artificial gravity, stable thermal conditions, and modular expansion without the constraints imposed by fixed gravity or surface geology. Economically, excess water, oxygen, and hydrogen production enables propellant export, in-space manufacturing support, and servicing of other space assets. Over time, Kepler Station transitions from a resource consumer to a net contributor within near-Earth space infrastructure.`
  },
  
  heliosAI: {
    purpose: `HELIOS serves as the central AI management system coordinating all settlement operations including life support monitoring, energy distribution, emergency response protocols, resource allocation, and system diagnostics.`,
    architecture: `The system operates on distributed computing architecture with redundant nodes throughout the settlement. Core functions include: real-time sensor monitoring, predictive maintenance, resource optimization algorithms, emergency response automation, and human-interface protocols.`,
    lifeSupport: `HELIOS continuously monitors atmospheric composition (O2, CO2, N2 levels), water recycling efficiency, waste processing systems, and agricultural output. Automated adjustments maintain optimal conditions with human oversight for critical decisions.`,
    emergency: `Emergency protocols include: rapid depressurization response, fire suppression, radiation event protocols, medical emergency coordination, and evacuation procedures. All systems maintain 30-day autonomous operation capability.`,
    knowledgeModel: `HELIOS maintains a continuously updated, high-fidelity internal model of Kepler Station and its interaction with asteroid Bennu. This model encompasses physical systems, biological processes, energy flows, structural dynamics, environmental hazards, and human-driven demand patterns. HELIOS does not merely monitor values in isolation; it understands how changes in one domain propagate through the entire settlement.`,
    knowledgeDomains: `HELIOS maintains awareness across multiple domains: Physical & Environmental (atmospheric state, radiation environment), Structural & Mechanical (rotating habitat dynamics, Bennu interface), Energy & Power Systems (generation, storage, consumption), Life Support & Biological Systems (water, agriculture), Waste & Closed-Loop Material Systems, Population & Human Activity (aggregate models only), Emergency & Failure Knowledge, Expansion & Scalability, and Ethical Constraints.`,
    ethicalConstraints: `HELIOS is explicitly forbidden from: making governance decisions, enforcing laws or discipline, controlling reproduction or population size, manipulating behavior, or making value judgments. HELIOS does not know political preferences, cultural norms, or personal identities. Its knowledge domain ends where human autonomy begins.`,
    explainability: `Every HELIOS output includes: data sources used, reasoning steps, confidence estimates, and alternative options considered. All actions are logged permanently for human review.`
  },
  
  design: {
    structural: `The settlement consists of modular cylindrical and toroidal sections connected via pressurized corridors. Primary structure utilizes asteroid-derived materials supplemented with Earth-manufactured critical components. Core sections include: residential habitats, agricultural modules, industrial facilities, command center, and recreation areas.`,
    materials: `Base construction materials derived from asteroid include: iron-nickel alloys (structural framework), carbon composites (pressure vessels), regolith concrete (shielding), and extracted silicon (electronics). Earth-supplied materials limited to complex electronics, specialty alloys, and initial life support components.`,
    shielding: `Multi-layer radiation shielding: 3-5 meters regolith covering on outer surfaces, water-filled compartments providing secondary shielding, magnetic field generators for charged particle deflection, and solar storm shelters with enhanced protection. Total shielding equivalent to 1.5 meters water or 0.5 meters lead.`,
    asteroidAnchor: `The settlement is structurally anchored to the captured asteroid using reinforced connection points. The asteroid provides: mass foundation for rotation stability, mining access points, and additional shielding. Anchoring systems include expansion bolts, regolith stabilization, and structural reinforcement.`,
    rotation: `The habitat rotates at 1.9 RPM to generate 0.38g artificial gravity (Mars-like), sufficient for long-term health maintenance. Rotation radius of 225 meters. Adjustable rotation rates accommodate different gravity needs for various activities.`,
    deployment: `Human deployment occurs in phases: Phase 1 - Automated systems activation and verification (6 months), Phase 2 - Initial crew of 50 specialists (establish operations), Phase 3 - Expansion to 500 residents (18 months), Phase 4 - Full capacity of 1000+ residents with infrastructure for growth to 10,000.`
  },
  
  lifeSupport: {
    atmosphere: `Kepler Station maintains a breathable, Earth-normal atmosphere through a closed-loop environmental control system derived from and extended beyond NASA Environmental Control and Life Support System architecture. Atmospheric pressure within inhabited modules is maintained at approximately 101 kilopascals. Oxygen concentration is regulated at approximately 21 percent by volume. Carbon dioxide concentration is maintained below 3000 parts per million under nominal conditions, well below occupational exposure limits. Each inhabitant consumes approximately 0.84 kilograms of oxygen per day and produces approximately 1.0 kilogram of carbon dioxide per day. For a population of 1000 residents, total daily oxygen demand is approximately 840 kilograms and carbon dioxide production is approximately 1000 kilograms. Carbon dioxide removal is achieved through a combination of regenerative sorbent systems and biological uptake. Mechanical scrubbers provide rapid response capability, while agricultural and algal systems provide steady state absorption. Oxygen losses are replaced through water electrolysis using asteroid-derived water. Atmospheric circulation ensures complete air exchange within inhabited volumes every five minutes, preventing localized buildup of contaminants and ensuring uniform environmental conditions.`,
    waterRecovery: `Water is the central resource underpinning all life support functions. Kepler Station employs a fully closed-loop water recovery system with target recycling efficiency exceeding 95 percent. Each resident requires approximately 50 kilograms of water per day when accounting for drinking, hygiene, food production, and oxygen generation. For a population of 1000, total daily water throughput is approximately 50,000 kilograms. Recovered water streams include urine, hygiene wastewater, atmospheric condensate, and agricultural runoff. These streams are processed through multi-stage filtration, catalytic oxidation, and biological polishing to potable standards. With a 95 percent recovery efficiency, daily water losses are approximately 2,500 kilograms. These losses are replenished using water extracted from asteroid regolith. Annual make-up water demand is therefore approximately 912,500 kilograms. Water is stored in distributed tanks located around the habitat ring. These tanks serve a dual function as both resource storage and radiation shielding. Total on-board water storage capacity exceeds 30 days of full consumption, providing resilience against processing interruptions.`,
    wasteRecycling: `All waste streams are treated as recoverable resources. Organic waste includes human waste, food scraps, and inedible plant matter. Inorganic waste includes metals, polymers, and composite materials. Organic waste is processed through anaerobic digestion and microbial treatment, producing methane, carbon dioxide, and nutrient-rich residue. Methane is used as an auxiliary energy source, while nutrients are returned to agricultural systems. Inorganic waste is sorted and recycled through additive manufacturing and material reprocessing systems. Over time, this reduces dependency on Earth resupply for replacement components and tools. Solid waste disposal as an end state does not exist within the settlement. All material remains within the resource loop unless exported for external use. Target: 95% waste reduction through recycling, with minimal material export.`,
    agriculture: `Food production is a core life support function rather than a supplemental activity. Kepler Station uses a combination of hydroponic, aeroponic, and algal cultivation systems. Average daily caloric requirement per resident is approximately 2,500 kilocalories. For 1000 residents, total daily food energy demand is approximately 2.5 million kilocalories. High yield crops such as leafy greens, legumes, and tubers form the dietary base. Protein is supplemented through plant sources and controlled insect cultivation. Algae systems provide both protein and oxygen generation. Crop yields in controlled environment agriculture typically exceed 20 kilograms per square meter per year for leafy greens. Total agricultural growing area within the habitat ring is approximately 30,000 square meters, providing sufficient production capacity with redundancy. Agricultural systems are tightly coupled to atmosphere control. Carbon dioxide produced by residents is consumed by plants, while oxygen released by photosynthesis offsets metabolic demand. Target: 100% food production for 1000 residents with 20% surplus capacity.`,
    healthcare: `Life support extends beyond air and water to include long-term physical and mental health. Artificial gravity at Earth-equivalent levels prevents bone density loss, muscle atrophy, and cardiovascular deconditioning. Daily activity levels further support musculoskeletal health. Medical facilities include continuous health monitoring systems that track vital signs, sleep quality, and long-term trends. Data is anonymized and analyzed to detect population-level risks while preserving individual autonomy. Mental health is supported through access to naturalistic environments, stable circadian lighting, predictable daily routines, and social infrastructure. These factors are critical in preventing long-term isolation-related stress and cognitive decline. Medical facilities include: surgical suites, diagnostic imaging, pharmacy, rehabilitation center, and psychological support services. Telemedicine connections to Earth specialists, autonomous diagnostic AI, and comprehensive health monitoring systems. Population health tracking via wearable sensors and regular medical evaluations.`,
    solarPower: `Energy generation is primarily solar-based. Large photovoltaic arrays mounted on non-rotating trusses provide continuous power generation. At a heliocentric distance near 1 astronomical unit, solar irradiance is approximately 1,360 watts per square meter. Assuming 30 percent panel efficiency and an effective collection area of 20,000 square meters, total peak power generation is approximately 8.2 megawatts. Energy demand for life support, agriculture, industrial processing, and habitation is estimated at approximately 5 megawatts under nominal operation. This provides a comfortable generation margin for contingencies and expansion. Solar arrays are articulated to maintain optimal orientation and are shielded against micrometeoroid damage through redundancy and sectional isolation.`,
    energyStorage: `Energy storage ensures uninterrupted operation during peak demand, maintenance, or transient generation losses. Short-term storage is provided through high-capacity battery systems capable of sustaining full life support operation for a minimum of 12 hours. Long-term storage is provided through hydrogen produced during water electrolysis. Hydrogen is stored cryogenically and used in fuel cells to generate electricity during extended low generation periods. Round-trip efficiency of hydrogen energy storage is approximately 45 percent, which is acceptable given the abundance of water resources. Energy distribution is managed through a smart grid architecture with multiple redundant pathways. Life-critical systems are electrically isolated and protected against cascading failures. Additional systems include: lithium-ion battery banks (500 kWh capacity), flywheel storage for short-term fluctuations, and hydrogen fuel cells for extended backup (7-day autonomy). Redundant distribution networks ensure critical systems always have power.`,
    integratedStability: `Life support and energy systems are designed as a single integrated network. Water supports oxygen generation and energy storage. Energy supports water recovery and agriculture. Agriculture supports atmosphere control and nutrition. HELIOS continuously monitors these interdependencies, ensuring that changes in population, energy availability, or agricultural output do not destabilize the system. This integrated approach ensures that Kepler Station can sustain human life indefinitely under nominal operation and survive extended disruptions without catastrophic failure.`
  },
  
  safety: {
    radiation: `Radiation exposure represents one of the most significant long-term risks to human health in deep space. Outside Earth's magnetosphere, unshielded exposure averages approximately 0.6 to 0.7 sieverts per year, exceeding recommended lifetime limits. Kepler Station mitigates this risk primarily through passive shielding using asteroid-derived regolith and water. Living areas are surrounded by shielding equivalent to approximately 2.5 meters of compacted regolith or 5 meters of water, reducing annual radiation exposure to levels comparable to or below those experienced on Earth's surface. Water storage tanks are strategically positioned around inhabited volumes to provide additional radiation attenuation while serving operational needs. Sleeping quarters and medical facilities receive enhanced shielding to further reduce cumulative dose during prolonged occupancy. Environmental hazards such as micrometeoroid impacts are addressed through multi-layer pressure hulls and distributed structural segmentation. External surfaces incorporate sacrificial layers designed to absorb hypervelocity impacts without compromising internal pressure integrity. Thermal hazards are mitigated through redundant active thermal control systems combined with passive insulation. Temperature gradients within inhabited spaces are limited to less than 2 degrees Celsius under nominal operation.`,
    structural: `Structural safety is based on the assumption that failures will occur over multi-generational time scales. The habitat ring is divided into independently pressurized segments, each capable of sustaining life autonomously for extended periods. Pressure loss in one segment does not propagate to adjacent segments due to rapid isolation mechanisms that activate within seconds of detection. Structural health monitoring systems embedded throughout load-bearing elements continuously measure strain, vibration, and fatigue accumulation. Deviations from predicted behavior are detected well before structural limits are approached, enabling preventative maintenance rather than reactive repair. Critical load paths are duplicated. No single structural member failure can result in catastrophic collapse. Radiation shielding mass is structurally decoupled from primary load-bearing components to prevent shielding shifts from inducing failure. In the event of severe structural damage, contingency protocols prioritize life preservation over asset protection. Population relocation, temporary habitat contraction, and long-duration reduced capacity operation are planned and rehearsed scenarios.`,
    emergency: `Emergency preparedness is treated as an ongoing operational requirement rather than a static plan. All residents receive regular training in emergency response procedures including pressure loss, fire containment, radiation sheltering, and system isolation. Training frequency is scaled by role, with critical system operators undergoing advanced simulations multiple times per year. Fire risk is mitigated through strict material selection, compartmentalization, and atmospheric monitoring. Fire suppression systems rely on localized oxygen reduction and inert gas deployment rather than water flooding, preserving pressure integrity and minimizing collateral damage. Medical emergencies are addressed through on-board surgical capability, pharmaceutical reserves, and telemedicine support from Earth when communication latency allows. Medical systems are designed to operate independently for extended periods without external resupply. Emergency drills are conducted regularly and are deliberately routine. This normalization reduces panic response and ensures that emergency actions become instinctive rather than exceptional.`,
    resilience: `Resilience is defined not as the absence of failure, but as the ability to recover without systemic collapse. All critical systems are designed to operate in degraded modes. Life support can sustain reduced populations with reduced comfort indefinitely. Energy systems can prioritize essential loads while suspending non-critical activity. Resource reserves including water, oxygen, and food are maintained at levels sufficient to support the full population for extended periods in the absence of production. These reserves are physically distributed to prevent single point depletion. HELIOS supports resilience by providing early warning, impact assessment, and recovery planning. However, final recovery strategies are directed by human operators to ensure adaptability and ethical oversight. Long-term recovery plans emphasize repair, replacement, and gradual restoration rather than rapid return to full capacity. This reduces stress on remaining systems and preserves overall stability.`,
    psychological: `Psychological resilience is recognized as equally critical to physical safety. Extended isolation, confinement, and interdependence create unique stressors. Kepler Station mitigates these through environmental stability, predictable routines, access to green spaces, and strong community structures. Mental health support is integrated into healthcare services. Residents have access to confidential counseling, peer support networks, and structured conflict mediation. Social safety mechanisms prioritize early intervention. Minor conflicts are addressed before escalation through transparent communication and restorative processes. This prevents social fracture, which represents a systemic risk in closed environments. Cultural norms emphasize collective responsibility and mutual reliance rather than individual heroism. This framing supports cooperation during emergencies and reinforces trust in shared systems.`,
    continuousSafety: `Safety on Kepler Station is not a static condition but a continuous process informed by monitoring, experience, and adaptation. Incident reports, near misses, and system anomalies are documented and reviewed openly. Lessons learned are incorporated into procedures, training, and system upgrades. Because the settlement is intended to operate over multiple generations, safety practices are designed to evolve rather than ossify. This adaptability is essential for long-term survival in an environment where failure has immediate consequences. By treating safety, risk management, and resilience as foundational infrastructure rather than contingency planning, Kepler Station achieves survivability comparable to terrestrial cities despite its isolated and hostile environment.`
  },
  
  population: {
    structure: `Kepler Station is designed to support a stable, multi-generational population rather than a rotating workforce. Initial settlement begins with a founding population of approximately 1000 residents, selected to provide demographic balance, professional redundancy, and long-term social continuity. Population distribution is intentionally broad. Approximately 25 percent of residents are children and adolescents, 55 percent are working age adults, and 20 percent are older adults. This structure supports education, mentorship, institutional memory, and generational stability. Residents are not assigned singular lifelong roles. Each adult is trained in a primary profession and at least one secondary competency. For example, an agricultural specialist may also be trained in emergency response or systems maintenance. This redundancy reduces vulnerability to illness, attrition, or skill loss and improves resilience during emergencies. Critical roles include life support and systems engineering, healthcare and human performance, agriculture and food production, construction and maintenance, education, governance administration, and cultural coordination. Automation reduces routine labor demand, allowing residents to focus on oversight, creativity, and long-term planning rather than constant manual operation. Population growth is managed deliberately. Birth rates are aligned with life support capacity and habitat expansion schedules to avoid overstressing closed-loop systems. HELIOS provides population capacity forecasts, but final decisions remain under human governance authority.`,
    housing: `Housing is organized into neighborhood-scale clusters rather than uniform modules. Each neighborhood supports approximately 100 to 150 residents and includes private living units, shared kitchens or dining areas, recreational spaces, and access to green environments. Individual living units range from 30 to 70 square meters depending on household size. Units are modular and reconfigurable, allowing families to expand or contract their living space as circumstances change. This adaptability prevents forced relocation and supports long-term residency. Artificial gravity provides a familiar physical environment. Floors, ceilings, and vertical orientation behave identically to Earth. Lighting systems follow a 24-hour cycle with gradual transitions to support circadian rhythms and sleep health. Environmental conditions within living spaces are tightly controlled. Temperature is maintained between 20 and 24 degrees Celsius. Relative humidity is maintained between 40 and 60 percent. Ambient noise levels are kept below 35 decibels in residential areas, comparable to quiet suburban environments on Earth. Radiation shielding and pressure containment are integrated into structural walls rather than added as visible barriers. This ensures that living spaces feel domestic rather than industrial.`,
    education: `Education is treated as essential infrastructure. Children receive a comprehensive academic curriculum including mathematics, sciences, languages, history, and ethics, alongside space-specific education in systems thinking, environmental balance, and cooperative responsibility. Practical education is emphasized. Students participate in supervised agricultural work, maintenance simulations, and governance observation from an early age. This ensures that every resident understands how the settlement functions and why individual actions affect collective survival. Adult education is continuous. As systems evolve and technology changes, residents regularly participate in retraining programs and certification updates. This prevents skill stagnation and maintains operational competence across generations. Educational capacity is scaled for a student population of approximately 250 individuals at any given time. Class sizes are limited to maintain instructional quality and allow hands-on learning. Education also serves a cultural function by reinforcing shared values of stewardship, transparency, and collective responsibility rather than hierarchy or prestige. Education system includes: primary/secondary schools, technical training programs, university partnerships for higher education, adult continuing education, and research collaboration programs. Emphasis on STEM fields, space sciences, and settlement-specific skills.`,
    recreation: `Recreation and culture are treated as life support functions rather than luxuries. Long-term psychological health in isolated environments depends on meaningful leisure, creative expression, and social connection. Kepler Station includes dedicated recreational spaces such as sports areas, performance venues, art studios, and virtual reality environments. Physical recreation supports cardiovascular and musculoskeletal health, while creative activities support emotional resilience. Green spaces integrated into the habitat ring provide exposure to living plants, natural color variation, and seasonal change simulations. These environments reduce stress and cognitive fatigue associated with enclosed habitats. Cultural traditions develop organically over time. Events tied to orbital cycles, settlement milestones, and generational transitions provide a shared sense of identity. These traditions are not centrally planned but supported through infrastructure and community participation. Daily life is intentionally structured to feel ordinary. Residents attend school, go to work, share meals, exercise, and participate in governance. The goal is not to constantly remind inhabitants that they live in space, but to allow space to fade into the background of daily experience.`,
    heliosInteraction: `For most residents, HELIOS is rarely noticed. It manifests indirectly through stable air quality, clean water, predictable lighting, and reliable infrastructure. Residents do not issue commands to HELIOS. Instead, they interact with human-managed interfaces such as maintenance teams, educators, or governance bodies. This prevents anthropomorphization of the system and reinforces human responsibility. When anomalies occur, HELIOS provides alerts and recommendations through transparent reporting channels. These alerts are designed to be informative rather than alarming, preventing panic and maintaining trust. Education ensures that residents understand what HELIOS does and what it does not do. This knowledge prevents dependence, fear, or mythology from developing around the system.`,
    socialStability: `Social stability is maintained through transparency, participation, and predictability. Governance processes are open. Resource availability is clearly communicated. System limitations are explained rather than hidden. Conflict resolution mechanisms prioritize mediation and restorative processes rather than punishment. In a closed environment, social fracture represents a systemic risk and is treated accordingly. Because basic needs such as housing, food, healthcare, and education are guaranteed, residents are insulated from survival-driven competition. This allows focus on contribution, creativity, and communal well-being. Over time, Kepler Station develops a distinct cultural identity rooted in shared responsibility, technical literacy, and intergenerational continuity. This identity is essential for sustaining a permanent human presence beyond Earth.`,
    healthcare: `Comprehensive healthcare with: preventive medicine programs, routine health screenings, mental health services, reproductive health services, and emergency medical response. Integration with Earth medical institutions for complex cases via telemedicine.`
  },
  
  governance: {
    framework: `Kepler Station is governed through a structured, participatory system designed for long-term stability in a closed environment. Governance prioritizes transparency, redundancy, and adaptability rather than speed or concentration of power. The governing structure consists of three primary components. A legislative council responsible for policy and long-term planning. An executive administration responsible for implementation and operations. An independent oversight body responsible for review, audit, and dispute resolution. The legislative council is composed of elected representatives proportional to population size. Terms are staggered to ensure continuity and prevent abrupt policy shifts. Representation reflects neighborhoods rather than professions to avoid technocratic dominance. The executive administration manages infrastructure, logistics, education, healthcare coordination, and external relations. Executive roles are appointed based on demonstrated competence and are subject to periodic review and reconfirmation. The oversight body operates independently of both legislative and executive branches. Its role is to review decisions, audit system performance, investigate grievances, and ensure compliance with agreed governance principles. This separation is essential in a settlement where institutional failure directly threatens survival. Governance structures are codified but not rigid. Amendment mechanisms exist and are deliberately slow, requiring broad consensus to prevent instability while still allowing adaptation over generational timescales.`,
    heliosRole: `HELIOS does not govern Kepler Station. Its role within governance is strictly advisory and analytical. For governance decisions involving infrastructure, resource allocation, or long-term planning, HELIOS provides predictive modeling, scenario analysis, and quantified risk assessments. These outputs include confidence ranges, assumptions, and explicit uncertainties. HELIOS cannot issue binding directives, enforce policy, or prioritize one population group over another. It has no authority over law, justice, or social norms. All HELIOS generated recommendations are logged, reviewable, and contestable. Human decision makers are required to explicitly acknowledge when recommendations are accepted, modified, or rejected. This ensures accountability and prevents algorithmic authority creep. By functioning as an analytical tool rather than a decision maker, HELIOS reduces cognitive load on governance bodies while preserving human responsibility and ethical agency.`,
    economic: `Kepler Station operates under a hybrid economic model optimized for a closed environment with finite resources. Basic needs including housing, food, water, healthcare, education, and access to energy are guaranteed to all residents. This baseline provision removes survival-driven competition, which is destabilizing in isolated settlements, and allows economic activity to focus on contribution, innovation, and long-term value. Beyond basic provision, a contribution-based economic layer exists. Residents earn discretionary credits through professional work, research, creative output, education, and community service. These credits provide access to non-essential goods, expanded living space options, specialized equipment time, and recreational privileges. Resource allocation for critical systems is managed centrally based on engineering constraints and population needs. Non-critical resource use is decentralized and guided by pricing signals designed to encourage efficiency without restricting access. External economic activity includes export of excess resources such as water-derived propellant, oxygen, and technical services for other space assets. These exports generate strategic value rather than traditional currency accumulation and are reinvested into infrastructure resilience and expansion. No speculative financial markets exist within the settlement. Economic activity is grounded in physical resource flows, labor contribution, and system capacity. This prevents instability driven by abstraction disconnected from survival realities.`,
    economicStability: `Economic stability is maintained through transparency and predictability. Resource availability, production rates, and system limits are communicated openly to residents. This prevents misinformation-driven panic or hoarding behaviors. Population growth, habitat expansion, and industrial scaling are coordinated through long-term planning cycles spanning decades rather than years. This aligns economic decisions with infrastructure timelines and prevents overextension. Automation reduces routine labor demand, but meaningful work remains essential for social cohesion. Work is structured to emphasize responsibility, skill development, and contribution rather than productivity maximization. Because Kepler Station is not profit-driven, success is measured through system stability, health outcomes, educational attainment, and long-term resilience rather than economic growth metrics alone.`,
    governanceAsLifeSupport: `In a closed settlement, governance is not abstract. Poor governance decisions can directly lead to system failure and loss of life. For this reason, governance is treated as a life support function alongside air, water, and energy. Decision-making processes are designed to be slow, deliberative, and evidence-based. Emergency authority exists but is narrowly scoped and time-limited. Civic education ensures that all residents understand how governance functions and how to participate effectively. This shared literacy prevents power concentration and disengagement. Over time, governance becomes routine rather than dramatic. Residents expect stability, accountability, and continuity. This normalization is essential for sustaining a permanent human settlement beyond Earth.`
  },
  
  growth: {
    expansion: `Expansion phases: Phase 1 (0-2 years): Initial deployment and operational establishment. Phase 2 (2-5 years): Population growth to 2000, infrastructure expansion, industrial development. Phase 3 (5-10 years): Population 5000, additional modules, specialized facilities. Phase 4 (10+ years): Population 10,000+, self-sustaining economy, multiple settlements. Each phase includes specific infrastructure additions and resource requirements.`,
    scalability: `Kepler Station is not intended to be unique. It is designed as a reference model. Systems architecture, governance principles, and development strategies are documented explicitly to support replication at other near-Earth asteroids. Each future settlement can adapt the model to its specific resource profile, population size, and orbital environment. Rather than concentrating growth into a single structure, Kepler Station supports a distributed expansion strategy. Multiple smaller settlements reduce systemic risk and allow cultural and technical diversity to emerge. Over time, this network of settlements forms a resilient human presence in near-Earth space without reliance on any single point of failure. The ethical success of Kepler Station is measured not by scale or speed, but by its ability to sustain human life responsibly while enabling future generations to choose their own paths.`
  },
  
  ethics: {
    aiEthics: `Kepler Station is designed around the principle that technology exists to support human agency rather than replace it. HELIOS is intentionally constrained to function as an analytical and operational support system, not a decision-making authority. Ethical safeguards are embedded at the architectural level rather than implemented through policy alone. HELIOS cannot issue social directives, enforce rules, or make judgments about individual behavior. Its outputs are advisory, transparent, and reviewable. Human autonomy is preserved through distributed oversight and mandatory human confirmation for any action beyond immediate safety stabilization. No individual or subsystem has unilateral control over critical infrastructure. Education ensures that every generation understands the capabilities and limitations of HELIOS. This prevents dependency, mystification, or erosion of human responsibility over time. By designing AI as infrastructure rather than authority, Kepler Station avoids both technological overreach and cultural dependence.`,
    legalFramework: `Kepler Station operates within the framework established by existing international space law, particularly the Outer Space Treaty. The settlement does not claim sovereignty over the asteroid or surrounding space. The asteroid is treated as a shared natural resource utilized for peaceful purposes. Resource extraction is conducted in accordance with emerging norms for in-situ resource utilization, emphasizing non-appropriation and non-exclusion. Governance authority applies only to residents of Kepler Station and its internal operations. External interactions are conducted transparently and without militarization. Legal ambiguity is addressed through cooperative agreements rather than unilateral action. As space law evolves, Kepler Station's governance framework is designed to adapt without undermining stability or human rights. This approach ensures legitimacy while avoiding precedents that could destabilize future space activity.`
  },
  
  // Research section - Add your research papers and studies here
  research: {
    heliosKnowledgeModel: `HELIOS Knowledge Model Documentation:

HELIOS maintains a continuously updated, high-fidelity internal model of Kepler Station and its interaction with asteroid Bennu. This model encompasses physical systems, biological processes, energy flows, structural dynamics, environmental hazards, and human-driven demand patterns. HELIOS does not merely monitor values in isolation; it understands how changes in one domain propagate through the entire settlement.

A. Physical & Environmental Knowledge:
- Atmospheric State: Tracks O2 (%), CO2 (ppm), N2 balance, pressure (kPa), temperature gradients, humidity. Understands human respiratory demand, acceptable physiological bounds, time-to-harm thresholds, and how atmospheric changes affect plant growth, fire risk, and material degradation. Predicts atmospheric drift and recommends corrective action.

- Radiation Environment: Tracks background galactic cosmic radiation, solar particle event flux, shielding effectiveness by location, cumulative dose exposure per zone. Knows Bennu's contribution to passive shielding, shielding distribution in habitat walls, safe exposure limits. Can predict radiation storms and recommend movement to storm shelters, load-shedding, and operational mode changes.

B. Structural & Mechanical Knowledge:
- Rotating Habitat Dynamics: Tracks rotation rate (rpm), angular momentum, bearing loads, vibration spectra, Coriolis-induced stress patterns. Understands mass redistribution effects, acceptable deviation before human discomfort, long-term fatigue accumulation. Predicts maintenance needs and flags instability.

- Bennu Interface & Anchoring: Tracks anchor point loads, regolith movement, truss strain, thermal expansion, material transfer rates. Understands Bennu as a rubble-pile asteroid with low cohesion, variable-gravity, non-uniform mass. Ensures no mechanical disturbances propagate into rotating habitat.

C. Energy & Power Systems Knowledge:
- Generation: Solar array output (real-time + forecast), shadowing effects, degradation rates
- Storage: Battery state-of-charge, fuel cell reserves, charge/discharge efficiency
- Consumption: Life support baseline, agricultural lighting, industrial operations, habitat heating/cooling
- HELIOS understands which systems are life-critical, which loads are deferrable, and how energy scarcity propagates. Schedules energy use proactively.

D. Life Support & Biological Systems Knowledge:
- Water Systems: Tracks water reserves (potable, industrial, shielding), recycling efficiency (%), contamination risk, emergency reserves. Understands water's dual role as shielding and life support, how shortages cascade into oxygen and food production.

- Agriculture & Food Systems: Tracks crop species distribution, growth stage, yield forecasts, nutrient cycles, lighting exposure, pollination. Understands nutritional requirements, crop redundancy, how plant health affects oxygen balance. Predicts food shortages months in advance.

E. Waste & Closed-Loop Material Systems:
Models organic waste streams, inorganic recycling flows, fertilizer production, biogas yield. Understands material conservation constraints, how inefficiencies accumulate, storage vs processing tradeoffs. Nothing is treated as "waste" — only delayed resources.

F. Population & Human Activity Knowledge:
Tracks population size, age distribution, activity cycles (sleep/work/recreation), healthcare system load, consumption rates. Understands how population behavior affects oxygen, food, and power demand. Does NOT profile individuals, monitor personal behavior, or make social decisions.

G. Emergency & Failure Knowledge:
Contains predefined models for: hull breaches, fire propagation, radiation storms, power collapse, agricultural failure, structural fatigue. For each scenario, knows detection signatures, time-to-critical thresholds, containment strategies, human response protocols. Can simulate outcomes and present ranked response paths.

H. Expansion & Scalability Knowledge:
Scales computationally per habitat ring, maintains independent yet coordinated control zones, prevents resource contention. Understands when expansion exceeds safe margins and when new construction threatens stability. Can recommend when not to expand.

I. Ethical Constraints & Forbidden Knowledge:
HELIOS is explicitly forbidden from: making governance decisions, enforcing laws or discipline, controlling reproduction or population size, manipulating behavior, making value judgments. HELIOS does not know political preferences, cultural norms, or personal identities. Its knowledge domain ends where human autonomy begins.

J. Explainability & Auditability:
Every HELIOS output includes: data sources used, reasoning steps, confidence estimates, alternative options considered. All actions are logged permanently for human review.`
  }
}

export function getKnowledgeContext(query: string): string {
  const lowerQuery = query.toLowerCase()
  const sections: string[] = []
  
  // Introduction queries
  if (lowerQuery.includes('introduction') || lowerQuery.includes('summary') || lowerQuery.includes('executive') || lowerQuery.includes('scope')) {
    sections.push(`INTRODUCTION:\n${HELIOS_KNOWLEDGE_BASE.introduction.executiveSummary}\n\nSCOPE: ${HELIOS_KNOWLEDGE_BASE.introduction.scope}`)
  }
  
  // Settlement overview
  if (lowerQuery.includes('mission') || lowerQuery.includes('vision') || lowerQuery.includes('purpose') || lowerQuery.includes('objective')) {
    sections.push(`MISSION: ${HELIOS_KNOWLEDGE_BASE.settlementOverview.missionStatement}\n\nVISION: ${HELIOS_KNOWLEDGE_BASE.settlementOverview.vision}`)
  }
  
  // Orbit and asteroid
  if (lowerQuery.includes('orbit') || lowerQuery.includes('orbital characteristics') || lowerQuery.includes('heliocentric') || lowerQuery.includes('station keeping') || lowerQuery.includes('delta v') || lowerQuery.includes('bennu orbit') || lowerQuery.includes('semi-major axis')) {
    sections.push(`ORBITAL CHARACTERISTICS:\n${HELIOS_KNOWLEDGE_BASE.orbitAndAsteroid.orbitalCharacteristics}`)
  }
  if (lowerQuery.includes('asteroid selection') || lowerQuery.includes('bennu') || lowerQuery.includes('asteroid profile') || lowerQuery.includes('rubble pile') || lowerQuery.includes('asteroid structure') || lowerQuery.includes('bennu selection')) {
    sections.push(`ASTEROID SELECTION AND RESOURCE PROFILE:\n${HELIOS_KNOWLEDGE_BASE.orbitAndAsteroid.asteroidSelection}`)
  }
  if (lowerQuery.includes('water content') || lowerQuery.includes('volatile content') || lowerQuery.includes('osiris-rex') || lowerQuery.includes('phyllosilicate') || lowerQuery.includes('water production') || lowerQuery.includes('water extraction')) {
    sections.push(`WATER AND VOLATILE CONTENT:\n${HELIOS_KNOWLEDGE_BASE.orbitAndAsteroid.waterContent}`)
  }
  if (lowerQuery.includes('oxygen production') || lowerQuery.includes('hydrogen production') || lowerQuery.includes('electrolysis') || lowerQuery.includes('oxygen hydrogen') || lowerQuery.includes('oxygen and hydrogen')) {
    sections.push(`OXYGEN AND HYDROGEN PRODUCTION:\n${HELIOS_KNOWLEDGE_BASE.orbitAndAsteroid.oxygenHydrogen}`)
  }
  if (lowerQuery.includes('regolith') || lowerQuery.includes('structural material') || lowerQuery.includes('shielding mass') || lowerQuery.includes('construction feedstock') || lowerQuery.includes('regolith processing')) {
    sections.push(`REGOLITH AND STRUCTURAL MATERIAL:\n${HELIOS_KNOWLEDGE_BASE.orbitAndAsteroid.regolith}`)
  }
  if (lowerQuery.includes('advantages') || lowerQuery.includes('strategic') || lowerQuery.includes('economic advantages') || lowerQuery.includes('asteroid anchored') || lowerQuery.includes('strategic advantages')) {
    sections.push(`STRATEGIC AND ECONOMIC ADVANTAGES:\n${HELIOS_KNOWLEDGE_BASE.orbitAndAsteroid.advantages}`)
  }
  if ((lowerQuery.includes('asteroid') || lowerQuery.includes('location') || lowerQuery.includes('position')) && !lowerQuery.includes('selection') && !lowerQuery.includes('advantages') && !lowerQuery.includes('water') && !lowerQuery.includes('oxygen') && !lowerQuery.includes('regolith')) {
    sections.push(`ORBITAL LOCATION AND ASTEROID:\n${HELIOS_KNOWLEDGE_BASE.orbitAndAsteroid.orbitalCharacteristics}\n\nASTEROID SELECTION: ${HELIOS_KNOWLEDGE_BASE.orbitAndAsteroid.asteroidSelection}\n\nADVANTAGES: ${HELIOS_KNOWLEDGE_BASE.orbitAndAsteroid.advantages}`)
  }
  
  // HELIOS AI
  if (lowerQuery.includes('helios') || lowerQuery.includes('ai') || lowerQuery.includes('system') || lowerQuery.includes('automation')) {
    sections.push(`HELIOS AI SYSTEM:\nPurpose: ${HELIOS_KNOWLEDGE_BASE.heliosAI.purpose}\n\nArchitecture: ${HELIOS_KNOWLEDGE_BASE.heliosAI.architecture}\n\nLife Support Management: ${HELIOS_KNOWLEDGE_BASE.heliosAI.lifeSupport}\n\nEmergency Response: ${HELIOS_KNOWLEDGE_BASE.heliosAI.emergency}\n\nKnowledge Model: ${HELIOS_KNOWLEDGE_BASE.heliosAI.knowledgeModel}\n\nKnowledge Domains: ${HELIOS_KNOWLEDGE_BASE.heliosAI.knowledgeDomains}\n\nEthical Constraints: ${HELIOS_KNOWLEDGE_BASE.heliosAI.ethicalConstraints}\n\nExplainability: ${HELIOS_KNOWLEDGE_BASE.heliosAI.explainability}`)
  }
  
  // HELIOS Knowledge Model queries
  if (lowerQuery.includes('knowledge model') || lowerQuery.includes('internal model') || lowerQuery.includes('digital twin') || lowerQuery.includes('kepler station')) {
    sections.push(`HELIOS KNOWLEDGE MODEL:\n${HELIOS_KNOWLEDGE_BASE.research.heliosKnowledgeModel}`)
  }
  
  // Specific domain queries
  if (lowerQuery.includes('atmospheric state') || lowerQuery.includes('atmosphere tracking')) {
    sections.push(`HELIOS tracks atmospheric state including O2 (%), CO2 (ppm), N2 balance, pressure (kPa), temperature gradients, and humidity. It understands human respiratory demand, acceptable physiological bounds, time-to-harm thresholds, and how atmospheric changes affect plant growth, fire risk, and material degradation.`)
  }
  
  if (lowerQuery.includes('radiation environment') || lowerQuery.includes('radiation tracking')) {
    sections.push(`HELIOS tracks background galactic cosmic radiation, solar particle event flux, shielding effectiveness by location, and cumulative dose exposure per zone. It knows Bennu's contribution to passive shielding and can predict radiation storms using heliophysical data.`)
  }
  
  if (lowerQuery.includes('rotating habitat') || lowerQuery.includes('rotation dynamics')) {
    sections.push(`HELIOS tracks rotation rate (rpm), angular momentum, bearing loads, vibration spectra, and Coriolis-induced stress patterns. It understands how mass redistribution affects stability and predicts maintenance needs.`)
  }
  
  if (lowerQuery.includes('energy balance') || lowerQuery.includes('power systems') || lowerQuery.includes('energy model')) {
    sections.push(`HELIOS maintains a settlement-wide energy balance model tracking solar array output, battery state-of-charge, fuel cell reserves, and consumption across life support, agriculture, industrial operations, and habitat systems. It schedules energy use proactively.`)
  }
  
  if (lowerQuery.includes('closed loop') || lowerQuery.includes('waste systems') || lowerQuery.includes('material recycling')) {
    sections.push(`HELIOS models organic waste streams, inorganic recycling flows, fertilizer production, and biogas yield. It understands material conservation constraints and that nothing is treated as "waste" — only delayed resources.`)
  }
  
  if (lowerQuery.includes('ethical') || lowerQuery.includes('forbidden') || lowerQuery.includes('constraints')) {
    sections.push(`HELIOS Ethical Constraints: HELIOS is explicitly forbidden from making governance decisions, enforcing laws, controlling reproduction or population size, manipulating behavior, or making value judgments. It does not know political preferences, cultural norms, or personal identities. Its knowledge domain ends where human autonomy begins.`)
  }
  
  if (lowerQuery.includes('explainability') || lowerQuery.includes('auditability') || lowerQuery.includes('reasoning')) {
    sections.push(`HELIOS Explainability: Every HELIOS output includes data sources used, reasoning steps, confidence estimates, and alternative options considered. All actions are logged permanently for human review.`)
  }
  
  // Design
  if (lowerQuery.includes('design') || lowerQuery.includes('structure') || lowerQuery.includes('construction') || lowerQuery.includes('materials')) {
    sections.push(`SETTLEMENT DESIGN:\nStructural Overview: ${HELIOS_KNOWLEDGE_BASE.design.structural}\n\nMaterials: ${HELIOS_KNOWLEDGE_BASE.design.materials}\n\nRadiation Shielding: ${HELIOS_KNOWLEDGE_BASE.design.shielding}\n\nAsteroid Anchoring: ${HELIOS_KNOWLEDGE_BASE.design.asteroidAnchor}\n\nRotation & Gravity: ${HELIOS_KNOWLEDGE_BASE.design.rotation}\n\nDeployment: ${HELIOS_KNOWLEDGE_BASE.design.deployment}`)
  }
  
  // Life support
  if (lowerQuery.includes('life support') || lowerQuery.includes('atmosphere') || lowerQuery.includes('air') || lowerQuery.includes('oxygen')) {
    sections.push(`LIFE SUPPORT - Atmosphere: ${HELIOS_KNOWLEDGE_BASE.lifeSupport.atmosphere}`)
  }
  if (lowerQuery.includes('water') || lowerQuery.includes('recycling') || lowerQuery.includes('recovery')) {
    sections.push(`LIFE SUPPORT - Water: ${HELIOS_KNOWLEDGE_BASE.lifeSupport.waterRecovery}`)
  }
  if (lowerQuery.includes('waste') || lowerQuery.includes('recycle')) {
    sections.push(`LIFE SUPPORT - Waste: ${HELIOS_KNOWLEDGE_BASE.lifeSupport.wasteRecycling}`)
  }
  if (lowerQuery.includes('food') || lowerQuery.includes('agriculture') || lowerQuery.includes('farm') || lowerQuery.includes('grow')) {
    sections.push(`LIFE SUPPORT - Agriculture: ${HELIOS_KNOWLEDGE_BASE.lifeSupport.agriculture}`)
  }
  if (lowerQuery.includes('healthcare') || lowerQuery.includes('medical') || lowerQuery.includes('health')) {
    sections.push(`LIFE SUPPORT - Healthcare: ${HELIOS_KNOWLEDGE_BASE.lifeSupport.healthcare}`)
  }
  if (lowerQuery.includes('solar') || lowerQuery.includes('power') || lowerQuery.includes('energy') || lowerQuery.includes('electricity') || lowerQuery.includes('generation')) {
    sections.push(`LIFE SUPPORT - Power Generation: ${HELIOS_KNOWLEDGE_BASE.lifeSupport.solarPower}\n\nEnergy Storage: ${HELIOS_KNOWLEDGE_BASE.lifeSupport.energyStorage}`)
  }
  if (lowerQuery.includes('integrated') || lowerQuery.includes('stability') || lowerQuery.includes('interdependencies') || lowerQuery.includes('life support network') || lowerQuery.includes('system integration')) {
    sections.push(`INTEGRATED LIFE SUPPORT STABILITY:\n${HELIOS_KNOWLEDGE_BASE.lifeSupport.integratedStability}`)
  }
  
  // Safety
  if (lowerQuery.includes('radiation') || lowerQuery.includes('environmental hazards') || lowerQuery.includes('micrometeoroid') || lowerQuery.includes('thermal hazards') || lowerQuery.includes('radiation exposure')) {
    sections.push(`RADIATION AND ENVIRONMENTAL HAZARDS:\n${HELIOS_KNOWLEDGE_BASE.safety.radiation}`)
  }
  if (lowerQuery.includes('structural') || lowerQuery.includes('redundancy') || lowerQuery.includes('failure response') || lowerQuery.includes('pressure loss') || lowerQuery.includes('structural health') || lowerQuery.includes('load bearing')) {
    sections.push(`STRUCTURAL REDUNDANCY AND FAILURE RESPONSE:\n${HELIOS_KNOWLEDGE_BASE.safety.structural}`)
  }
  if (lowerQuery.includes('emergency') || lowerQuery.includes('emergency protocols') || lowerQuery.includes('human preparedness') || lowerQuery.includes('fire') || lowerQuery.includes('emergency drills') || lowerQuery.includes('emergency response') || lowerQuery.includes('emergency training')) {
    sections.push(`EMERGENCY PROTOCOLS AND HUMAN PREPAREDNESS:\n${HELIOS_KNOWLEDGE_BASE.safety.emergency}`)
  }
  if (lowerQuery.includes('resilience') || lowerQuery.includes('system resilience') || lowerQuery.includes('recovery') || lowerQuery.includes('degraded modes') || lowerQuery.includes('resource reserves') || lowerQuery.includes('recovery planning')) {
    sections.push(`SYSTEM RESILIENCE AND RECOVERY:\n${HELIOS_KNOWLEDGE_BASE.safety.resilience}`)
  }
  if (lowerQuery.includes('psychological') || lowerQuery.includes('mental health') || lowerQuery.includes('social resilience') || lowerQuery.includes('psychological safety') || lowerQuery.includes('isolation') || lowerQuery.includes('confinement') || lowerQuery.includes('social safety')) {
    sections.push(`PSYCHOLOGICAL SAFETY AND SOCIAL RESILIENCE:\n${HELIOS_KNOWLEDGE_BASE.safety.psychological}`)
  }
  if (lowerQuery.includes('continuous safety') || lowerQuery.includes('safety process') || lowerQuery.includes('incident reports') || lowerQuery.includes('near misses') || lowerQuery.includes('safety evolution') || lowerQuery.includes('safety adaptation')) {
    sections.push(`SAFETY AS A CONTINUOUS PROCESS:\n${HELIOS_KNOWLEDGE_BASE.safety.continuousSafety}`)
  }
  if (lowerQuery.includes('safety') || lowerQuery.includes('shielding') || lowerQuery.includes('protection') || lowerQuery.includes('risk')) {
    sections.push(`SAFETY OVERVIEW:\nRadiation: ${HELIOS_KNOWLEDGE_BASE.safety.radiation}\n\nStructural: ${HELIOS_KNOWLEDGE_BASE.safety.structural}\n\nEmergency: ${HELIOS_KNOWLEDGE_BASE.safety.emergency}`)
  }
  
  // Population
  if (lowerQuery.includes('population') || lowerQuery.includes('people') || lowerQuery.includes('residents') || lowerQuery.includes('demographics') || lowerQuery.includes('population structure') || lowerQuery.includes('roles')) {
    sections.push(`POPULATION STRUCTURE AND ROLES: ${HELIOS_KNOWLEDGE_BASE.population.structure}`)
  }
  if (lowerQuery.includes('housing') || lowerQuery.includes('living conditions') || lowerQuery.includes('residential') || lowerQuery.includes('living units') || lowerQuery.includes('neighborhood')) {
    sections.push(`HOUSING AND LIVING CONDITIONS: ${HELIOS_KNOWLEDGE_BASE.population.housing}`)
  }
  if (lowerQuery.includes('education') || lowerQuery.includes('school') || lowerQuery.includes('learning') || lowerQuery.includes('skill development') || lowerQuery.includes('curriculum')) {
    sections.push(`EDUCATION AND SKILL DEVELOPMENT: ${HELIOS_KNOWLEDGE_BASE.population.education}`)
  }
  if (lowerQuery.includes('recreation') || lowerQuery.includes('culture') || lowerQuery.includes('community') || lowerQuery.includes('leisure') || lowerQuery.includes('social life') || lowerQuery.includes('daily life')) {
    sections.push(`RECREATION, CULTURE, AND COMMUNITY LIFE: ${HELIOS_KNOWLEDGE_BASE.population.recreation}`)
  }
  if (lowerQuery.includes('helios interaction') || lowerQuery.includes('helios in daily') || lowerQuery.includes('resident interaction') || lowerQuery.includes('daily helios')) {
    sections.push(`INTERACTION WITH HELIOS IN DAILY LIFE: ${HELIOS_KNOWLEDGE_BASE.population.heliosInteraction}`)
  }
  if (lowerQuery.includes('social stability') || lowerQuery.includes('long term stability') || lowerQuery.includes('conflict resolution') || lowerQuery.includes('cultural identity')) {
    sections.push(`LONG TERM SOCIAL STABILITY: ${HELIOS_KNOWLEDGE_BASE.population.socialStability}`)
  }
  
  // Governance
  if (lowerQuery.includes('governance') || lowerQuery.includes('government') || lowerQuery.includes('politics') || lowerQuery.includes('law') || lowerQuery.includes('governance framework') || lowerQuery.includes('legislative council') || lowerQuery.includes('executive administration') || lowerQuery.includes('oversight body')) {
    sections.push(`GOVERNANCE FRAMEWORK: ${HELIOS_KNOWLEDGE_BASE.governance.framework}`)
  }
  if (lowerQuery.includes('helios role') || lowerQuery.includes('helios in governance') || lowerQuery.includes('decision support') || lowerQuery.includes('helios advisory') || lowerQuery.includes('algorithmic authority') || lowerQuery.includes('helios governance')) {
    sections.push(`ROLE OF HELIOS IN DECISION SUPPORT: ${HELIOS_KNOWLEDGE_BASE.governance.heliosRole}`)
  }
  if (lowerQuery.includes('economy') || lowerQuery.includes('economic') || lowerQuery.includes('money') || lowerQuery.includes('trade') || lowerQuery.includes('resource allocation') || lowerQuery.includes('economic model') || lowerQuery.includes('contribution based') || lowerQuery.includes('discretionary credits')) {
    sections.push(`ECONOMIC MODEL AND RESOURCE ALLOCATION: ${HELIOS_KNOWLEDGE_BASE.governance.economic}`)
  }
  if (lowerQuery.includes('economic stability') || lowerQuery.includes('long term economic') || lowerQuery.includes('resource availability') || lowerQuery.includes('planning cycles') || lowerQuery.includes('economic planning')) {
    sections.push(`LONG TERM ECONOMIC STABILITY: ${HELIOS_KNOWLEDGE_BASE.governance.economicStability}`)
  }
  if (lowerQuery.includes('governance as life support') || lowerQuery.includes('governance life support') || lowerQuery.includes('civic education') || lowerQuery.includes('decision making processes') || lowerQuery.includes('governance function')) {
    sections.push(`GOVERNANCE AS A LIFE SUPPORT SYSTEM: ${HELIOS_KNOWLEDGE_BASE.governance.governanceAsLifeSupport}`)
  }
  
  // Growth
  if (lowerQuery.includes('growth') || lowerQuery.includes('expansion') || lowerQuery.includes('future') || lowerQuery.includes('plan') || lowerQuery.includes('expansion phases')) {
    sections.push(`GROWTH & EXPANSION: ${HELIOS_KNOWLEDGE_BASE.growth.expansion}`)
  }
  if (lowerQuery.includes('scalability') || lowerQuery.includes('future settlements') || lowerQuery.includes('reference model') || lowerQuery.includes('distributed expansion') || lowerQuery.includes('network of settlements')) {
    sections.push(`SCALABILITY AND FUTURE SETTLEMENTS: ${HELIOS_KNOWLEDGE_BASE.growth.scalability}`)
  }
  
  // Ethics and Legal
  if (lowerQuery.includes('ai ethics') || lowerQuery.includes('human autonomy') || lowerQuery.includes('ethical safeguards') || lowerQuery.includes('ai authority') || lowerQuery.includes('technology support') || lowerQuery.includes('helios ethics') || lowerQuery.includes('ethical considerations')) {
    sections.push(`AI ETHICS AND HUMAN AUTONOMY: ${HELIOS_KNOWLEDGE_BASE.ethics.aiEthics}`)
  }
  if (lowerQuery.includes('legal framework') || lowerQuery.includes('space law') || lowerQuery.includes('outer space treaty') || lowerQuery.includes('sovereignty') || lowerQuery.includes('resource utilization') || lowerQuery.includes('international space law') || lowerQuery.includes('legal considerations')) {
    sections.push(`LEGAL FRAMEWORK AND SPACE LAW: ${HELIOS_KNOWLEDGE_BASE.ethics.legalFramework}`)
  }
  
  // Research queries
  if (lowerQuery.includes('research') || lowerQuery.includes('study') || lowerQuery.includes('paper') || lowerQuery.includes('findings')) {
    const researchEntries = Object.entries(HELIOS_KNOWLEDGE_BASE.research)
    if (researchEntries.length > 0) {
      const researchText = researchEntries.map(([key, value]) => 
        `RESEARCH - ${key}: ${value}`
      ).join('\n\n')
      sections.push(researchText)
    }
  }
  
  // If no specific match, provide overview
  if (sections.length === 0) {
    return `HELIOS Space Settlement Overview:\n\n${Object.values(HELIOS_KNOWLEDGE_BASE.introduction).join('\n\n')}\n\nFor specific information, please ask about: Introduction, Mission/Vision, Orbit & Asteroid, HELIOS AI, Design, Life Support, Safety, Population, Governance, or Growth & Expansion.`
  }
  
  return sections.join('\n\n---\n\n')
}